# This is the default, built-in configuration for Clara.
# It is used when no user-provided 'config.yaml' is found.
#
# To customize Clara, create your own 'config.yaml' and place it in:
# - The same directory as the 'clara' binary
# - ~/.config/clara/config.yaml
# - /etc/clara/config.yaml

services: []
routes: []